export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_OPEN_FORM = 'TOGGLE_OPEN_FORM';
export const TOGGLE_OPEN_COLLAPSE = 'TOGGLE_OPEN_COLLAPSE';
export const ADD_VISIT = 'ADD_VISIT';